
package ec.mileniumtech.educafacil.service.sri.recepcion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RecepcionComprobantesOfflineService", targetNamespace = "http://ec.gob.sri.ws.recepcion", wsdlLocation = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl")
public class RecepcionComprobantesOfflineService
    extends Service
{

    private static final URL RECEPCIONCOMPROBANTESOFFLINESERVICE_WSDL_LOCATION;
    private static final WebServiceException RECEPCIONCOMPROBANTESOFFLINESERVICE_EXCEPTION;
    private static final QName RECEPCIONCOMPROBANTESOFFLINESERVICE_QNAME = new QName("http://ec.gob.sri.ws.recepcion", "RecepcionComprobantesOfflineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEPCIONCOMPROBANTESOFFLINESERVICE_WSDL_LOCATION = url;
        RECEPCIONCOMPROBANTESOFFLINESERVICE_EXCEPTION = e;
    }

    public RecepcionComprobantesOfflineService() {
        super(__getWsdlLocation(), RECEPCIONCOMPROBANTESOFFLINESERVICE_QNAME);
    }

    public RecepcionComprobantesOfflineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEPCIONCOMPROBANTESOFFLINESERVICE_QNAME, features);
    }

    public RecepcionComprobantesOfflineService(URL wsdlLocation) {
        super(wsdlLocation, RECEPCIONCOMPROBANTESOFFLINESERVICE_QNAME);
    }

    public RecepcionComprobantesOfflineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEPCIONCOMPROBANTESOFFLINESERVICE_QNAME, features);
    }

    public RecepcionComprobantesOfflineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecepcionComprobantesOfflineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecepcionComprobantesOffline
     */
    @WebEndpoint(name = "RecepcionComprobantesOfflinePort")
    public RecepcionComprobantesOffline getRecepcionComprobantesOfflinePort() {
        return super.getPort(new QName("http://ec.gob.sri.ws.recepcion", "RecepcionComprobantesOfflinePort"), RecepcionComprobantesOffline.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecepcionComprobantesOffline
     */
    @WebEndpoint(name = "RecepcionComprobantesOfflinePort")
    public RecepcionComprobantesOffline getRecepcionComprobantesOfflinePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ec.gob.sri.ws.recepcion", "RecepcionComprobantesOfflinePort"), RecepcionComprobantesOffline.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEPCIONCOMPROBANTESOFFLINESERVICE_EXCEPTION!= null) {
            throw RECEPCIONCOMPROBANTESOFFLINESERVICE_EXCEPTION;
        }
        return RECEPCIONCOMPROBANTESOFFLINESERVICE_WSDL_LOCATION;
    }

}
